config/routes.rb
Rails.application.routes.draw do
  
  root to: 'main#home'
  # resources :categories
  # resources :follows, only: [:index, :create, :destroy]
  # resources :reviews
  resources :manufacturers, only: [:index, :search, :show] do 
    resources :products, only: [:new, :create]
  end 
  resources :products, only: [:new, :create, :show, :edit, :update] do 
    resources :reviews, only: [:new, :create, :show, :edit, :update]
  end 
  resources :users, only: [:new, :create, :show]

  # get '/' to 'main#home'
  get '/login', to: 'sessions#login'
  post '/login', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy'
  post '/products/new', to: 'products#create'
  get '/auth/:provider/callback', to: 'sessions#omniauth'
  post '/products/:id/reviews/new', to: 'reviews#create'
  post '/users/:user_id/create_follow', to: 'follows#create', as: 'create_follow'
  post '/users/:user_id/unfollow', to: 'follows#unfollow', as: 'unfollow'

  post '/reviews/:id', to: 'reviews#destroy', as: 'delete_review'

  # follows routes
  get '/users/:user_id/following', to: 'follows#following', as: 'user_following'
  get '/users/:user_id/followers', to:  'follows#followers', as: 'user_follower'

  # post '/users/:user_id/unfollow, to: 'follows#destroy'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_and_belongs_to_many :products
    has_many :reviews
    has_many :manufacturers, through: :products 

    has_many :received_follows, foreign_key: :followed_user_id, class_name: "Follow" #return array of follows for given user
    has_many :followers, through: :received_follows, source: :follower #return an array of followers
    has_many :given_follows, foreign_key: :follower_id, class_name: "Follow" #returns who a given user follows
    has_many :followings, through: :given_follows, source: :followed_user #aliasing
    # user.followers & user.followings
    
    validates :name, presence: true
    validates :email, presence: true, uniqueness: true 
    validates :username, presence: true, uniqueness: true
    #, length: { in: 5..15}, confirmation: true, unless: -> { password.blank? }, message: "Username must be between 5-15 charaacters"
    # validates :password, length: { minimum: 6}, message: "Password must include at least 6 charactrs"


    # NEED TO refactor from controller
    def following?(other_user)
        followings.include?(other_user)
    end
   
    def follow(other_user)
        # assign current user to other user's followings
        followings.update()
    end

    def unfollow(other_user)
        followings.find_by(followed_user_id: other_user).destroy
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :require_log_in, only: [:show]

    def new
        if logged_in?
            redirect_to user_path(current_user)
          else
            @user = User.new
            # error message
            # 
            # flash.now[:danger] = "MSG TXT" if @user.empty?
        end
    end 

    def create
        @user = User.create(user_params)
        if @user.valid?
            @user.save
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else
            render :new
        end
    end 

    def show
        @user = User.find_by(id: params[:id])
    end 
      
    private

    def user_params
        params.require(:user).permit(:name, :username, :email, :password)
    end 
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<%= render partial: 'layouts/errors', locals: {object: @user }%>

<div id="formContent">
<h3>Create Your Account</h3>
<%= form_with(model: @user, local: true) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %><br>

    <%= f.label :username %>
    <%= f.text_field :username %><br>

    <%= f.label :email %>
    <%= f.email_field(:email) %><br>

    <%= f.label :password %>
    <%= f.password_field(:password) %><br>

    <%= f.submit "Create Account" %>

    <% end %>
    <%= link_to 'OR Proceed with Google', '/auth/google_oauth2' %>

</div>

app/views/users/show.html.erb
<div class="media">
    <div class="media-body">
        <%= @user.name %><br>
        <%= link_to "Following:", user_following_path(@user) %>  <%= @user.followings.size %><br>
        <%= link_to "Followers:", user_follower_path(@user) %> <%= @user.followers.size %>
        <%= render 'follows/follow-btn', {object: @user } %>

    </div>
</div>

<div class="media">
    <div class="media-body">

        <h3>My Products</h3>

        <% @user.products.each do |product| %>
            <ul>
                <li><b><%= link_to product.name, product_path(product) %></b> by 
                <%= link_to product.manufacturer.name, manufacturer_path(product.manufacturer_id) %><br></li>
                <%= product.category.name %><br>
                <%= number_to_currency(product.price) %></li>
            </ul>
            <br>
    <% end %>

    </div>
</div>