config/routes.rb
Rails.application.routes.draw do
  
  root to: 'main#home'
  # resources :categories
  # resources :follows, only: [:index, :create, :destroy]
  # resources :reviews
  resources :manufacturers, only: [:index, :search, :show] do 
    resources :products, only: [:new, :create]
  end 
  resources :products, only: [:new, :create, :show, :edit, :update] do 
    resources :reviews, only: [:new, :create, :show, :edit, :update]
  end 
  resources :users, only: [:new, :create, :show]

  # get '/' to 'main#home'
  get '/login', to: 'sessions#login'
  post '/login', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy'
  post '/products/new', to: 'products#create'
  get '/auth/:provider/callback', to: 'sessions#omniauth'
  post '/products/:id/reviews/new', to: 'reviews#create'
  post '/users/:user_id/create_follow', to: 'follows#create', as: 'create_follow'
  post '/users/:user_id/unfollow', to: 'follows#unfollow', as: 'unfollow'

  post '/reviews/:id', to: 'reviews#destroy', as: 'delete_review'

  # follows routes
  get '/users/:user_id/following', to: 'follows#following', as: 'user_following'
  get '/users/:user_id/followers', to:  'follows#followers', as: 'user_follower'

  # post '/users/:user_id/unfollow, to: 'follows#destroy'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/follow.rb
class Follow < ApplicationRecord
    # belongs_to :follower, foreign_key: 'user_id', class_name: 'User'
    # belongs_to :following, foreign_key: 'following_id', class_name: 'User'
    # user who follows the other user -- create instance method called follower. Find follower_id's user
    belongs_to :follower, foreign_key: :follower_id, class_name: "User"

    # user who receives the follow
    # given a follow instance, return user instance for user being followed
    belongs_to :followed_user, foreign_key: :followed_user_id, class_name: "User"

end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
    before_action :require_log_in

    def index
        @user = current_user.id 
    #    Following
        #followers
    end
    
    def create
        @user = User.find_by(id: params[:user_id])
        if current_user.followings << @user
            redirect_to user_path(@user)
        else 
            # flash
            redirect_to user_path(@user)
        end 
    end 

#     2.6.1 :001 > User.first.followings
#   User Load (1.0ms)  SELECT "users".* FROM "users" ORDER BY "users"."id" ASC LIMIT $1  [["LIMIT", 1]]
#   User Load (1.4ms)  SELECT "users".* FROM "users" INNER JOIN "follows" ON "users"."id" = "follows"."followed_user_id" WHERE "follows"."follower_id" = $1 LIMIT $2  [["follower_id", 1], ["LIMIT", 11]]

    def unfollow
        @user = User.find_by(id: params[:user_id])
        relationship = current_user.given_follows.find_by(followed_user_id: @user)
        # binding.pry
        if relationship.destroy
            redirect_to user_path(@user)
        else 
            # 
            redirect_to user_path(@user)
        end 
    end 

    def followers 
        params[:user_id] && @user = User.find_by_id(params[:user_id])
        @follows = @user.followers 
    end 

    def following 
        params[:user_id] && @user = User.find_by_id(params[:user_id])
        @follows = @user.followings 
    end 


end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/views/follows/_follow-btn.html.erb
<% if @user != current_user %>
    <% if current_user.followings.include?(@user) %>
        <div class="follow-button">
        <%= button_to "Unfollow", unfollow_path(@user) %>
        </div>
    <% else %>
        <div class="follow-button">
        <%= button_to "Follow", create_follow_path(@user) %>
        </div>
    <%end %>
<% end %>

app/views/follows/followers.html.erb
<%= link_to @user.name, user_path(@user) %> followers:


<% if @follows.size == 0 %>
    <p>There are no followers</p>
<% else %>
    <% @follows.each do |f| %>
        <ul>
        <li><%= link_to f.name, user_path(f)%></li>
        </ul>
    <% end %>
<% end %>

app/views/follows/following.html.erb
<%= link_to @user.name, user_path(@user) %> follows:

<% if @follows.size == 0 %>
    <p>There are no followers</p>
<% else %>
    <% @follows.each do |f| %>
        <ul>
        <li><%= link_to f.name, user_path(f)%></li>
        </ul>
    <% end %>
<% end %>