config/routes.rb
Rails.application.routes.draw do
  
  root to: 'main#home'
  # resources :categories
  # resources :follows, only: [:index, :create, :destroy]
  # resources :reviews
  resources :manufacturers, only: [:index, :search, :show] do 
    resources :products, only: [:new, :create]
  end 
  resources :products, only: [:new, :create, :show, :edit, :update] do 
    resources :reviews, only: [:new, :create, :show, :edit, :update]
  end 
  resources :users, only: [:new, :create, :show]

  # get '/' to 'main#home'
  get '/login', to: 'sessions#login'
  post '/login', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy'
  post '/products/new', to: 'products#create'
  get '/auth/:provider/callback', to: 'sessions#omniauth'
  post '/products/:id/reviews/new', to: 'reviews#create'
  post '/users/:user_id/create_follow', to: 'follows#create', as: 'create_follow'
  post '/users/:user_id/unfollow', to: 'follows#unfollow', as: 'unfollow'

  post '/reviews/:id', to: 'reviews#destroy', as: 'delete_review'

  # follows routes
  get '/users/:user_id/following', to: 'follows#following', as: 'user_following'
  get '/users/:user_id/followers', to:  'follows#followers', as: 'user_follower'

  # post '/users/:user_id/unfollow, to: 'follows#destroy'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :manufacturer
  belongs_to :category
  has_and_belongs_to_many :users
  has_many :reviews

  accepts_nested_attributes_for :manufacturer, reject_if: proc {|attr| attr['name'].blank? }
  accepts_nested_attributes_for :reviews 

  scope :alphabetize, -> (m_id){where(manufacturer_id: m_id).order('name asc')}

  def avg_rating
    if self.reviews.count < 1 
      "No reviews"
    else 
      sum = self.reviews.map {|review| review['rating']}.inject(0, :+)
      avg = (sum / self.reviews.count).round(2)
    end 
  end 


end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    before_action :require_log_in, only: [:new, :create, :edit, :update]

    def new
        # nested
        if params[:manufacturer_id] && @manufacturer = Manufacturer.find_by(id: params[:manufacturer_id])
            @product = @manufacturer.products.build 
        else 
            @product = Product.new
            @product.build_manufacturer #create empty manufacturer
            @product.category.try(:id)

        end 
    end 

    def create
        product = Product.find_by(name: params[:product][:name],
            manufacturer_id: params[:product][:manufacturer_id])
        if product
            product.update(user_ids: current_user.id)
            redirect_to product_path(product)
        else 
            @product = Product.create(
                params.require(:product).permit(:name, :price, :category_id,
            :manufacturer_id, manufacturer_attributes: [:name])
            )
            if @product.save 
                @product.update(user_ids: current_user.id) 
                # binding.pry
                redirect_to product_path(@product)
            else 
                redirect_to new_product_path
            end 
        end 
    end 

    def show
        product_helper
        # @reviews = Review.most_recent(@product.id)
    end 

    def edit
        product_helper
    end 

    def update 
        product_helper
        @product.update(product_params)
        if @product.save 
            redirect_to product_path(@product )
        else 
            render :edit 
        end 
    end 

    private 

    def product_params
        params.require(:product).permit(:name, :price, :category,
        :body_part,
        mmanufacturer_attributes: [:id, :name]
        )
    end 

    def product_helper
        @product = Product.find_by(id: params[:id])
    end 

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= f.label :name %>
<%= f.text_field :name, list: "products_autcomplete" %><br>
<datalist id="products_autocomplete">
    <% Product.all.each do |product| %>
      <option value="<%= product.name %>">
    <% end %>
  </datalist>

<%= f.label :price %>
<%= f.number_field :price, value: @product.price ? '%.2f' % @product.price : nil, min: 0, step: 0.01 %><br>

<%= f.label :category_id %>
<%= f.collection_select :category_id, Category.all.sort_by{|c| c.name}, :id, :name, prompt: true  %><br>

app/views/products/edit.html.erb
<%= form_with(model: @product) do |f| %>
    <%= render 'form', f: f %>
    <%= f.label :manufacturer_id %>
    <%= f.collection_select :manufacturer_id,
        Manufacturer.all.sort_by{|m| m.name}, :id, :name, prompt: true  %><br>
    <%= f.submit "Update" %>

    <% end %>

app/views/products/new.html.erb
<%= render partial: 'layouts/errors', locals: {object: @product } %>

<h3>Add a New Product</h3>

<%= form_with(model: @product, local: true) do |f| %>
    <%= render 'form', {f: f} %>

        <% if @manufacturer.nil? %>
            <%= f.label :manufacturer_id %>
            <%= f.collection_select :manufacturer_id, Manufacturer.all.sort_by{|m| m.name}, :id, :name, prompt: true  %>
            <h4>Or Create a New Manufacturer</h4>
            <%= f.fields_for :manufacturer do |m_field| %>
                <%= m_field.label :name %>
                <%= m_field.text_field :name %><br>
                <% end %>
            <% else %>
                <%= f.hidden_field :manufacturer_id %>
            <% end %>


    <%= f.submit "Create" %>
    <% end %>

app/views/products/show.html.erb
<div class="media">
    <div class="media-body">
    <%= @product.name %> by <%= link_to @product.manufacturer.name, manufacturer_path(@product.manufacturer) %><br>
    Average Rating: <%= @product.avg_rating %><br>
    </div>
</div>



<div class="media">
    <div class="media-body">
    <% if logged_in? %>
        <% if !@product.reviews.find_by(user_id: current_user.id) %>
        <%= link_to "Add Review", new_product_review_path(@product) %> ||
        <%= link_to "Edit Product", edit_product_path(@product) %><br>
    <% else %>
        <%= link_to "Edit Product", edit_product_path(@product) %> || 
        <%= link_to "Edit My Review", edit_product_review_path(@product) %>
    <% end %>
<% end %>
</div>
</div>

<% if @product.reviews %>
<% @product.reviews.each do |r| %>
    <div class="media-box-container">
    <div class="media comment-box">
    <div class="media-body">
    <p class="media-heading"><%= link_to r.user.name, user_path(r.user) %>:</p>
    <%= r.comment %><br>
    Rating: <%= r.rating %><br>
    <%= r.updated_at %>
    </div>
    </div>
    </div>
    <br></br>
    <!-- link_to "All Reviews", review_path(@product) -->
<% end %>
<% else %>
    <p>"There are no reviews"</p>
<% end %>