config/routes.rb
Rails.application.routes.draw do
  
  root to: 'main#home'
  # resources :categories
  # resources :follows, only: [:index, :create, :destroy]
  # resources :reviews
  resources :manufacturers, only: [:index, :search, :show] do 
    resources :products, only: [:new, :create]
  end 
  resources :products, only: [:new, :create, :show, :edit, :update] do 
    resources :reviews, only: [:new, :create, :show, :edit, :update]
  end 
  resources :users, only: [:new, :create, :show]

  # get '/' to 'main#home'
  get '/login', to: 'sessions#login'
  post '/login', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy'
  post '/products/new', to: 'products#create'
  get '/auth/:provider/callback', to: 'sessions#omniauth'
  post '/products/:id/reviews/new', to: 'reviews#create'
  post '/users/:user_id/create_follow', to: 'follows#create', as: 'create_follow'
  post '/users/:user_id/unfollow', to: 'follows#unfollow', as: 'unfollow'

  post '/reviews/:id', to: 'reviews#destroy', as: 'delete_review'

  # follows routes
  get '/users/:user_id/following', to: 'follows#following', as: 'user_following'
  get '/users/:user_id/followers', to:  'follows#followers', as: 'user_follower'

  # post '/users/:user_id/unfollow, to: 'follows#destroy'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/manufacturer.rb
class Manufacturer < ApplicationRecord
    has_many :products
    has_many :reviews, through: :products 
    has_many :categories, through: :products

    def self.search(search) 
        if search != nil
            manufacturer = Manufacturer.find_by(name: search)
            if manufacturer
                self.where(id: manufacturer)
            else
                # if nothing is found
                Manufacturer.all.sort_by {|m| m.name}
            end 
        else 
            # if search is blank
            Manufacturer.all.sort_by {|m| m.name}
        end 
    end
end

app/controllers/manufacturers_controller.rb
class ManufacturersController < ApplicationController

    def index 
        @manufacturers = Manufacturer.search(params[:search])
    end

    def show
        @manufacturer = Manufacturer.find_by(id: params[:id])
        @products = Product.alphabetize(@manufacturer.id)
    end 
    
end

app/helpers/manufacturers_helper.rb
module ManufacturersHelper
    def ratings?
        @manufacturer.products.each do |product|
            if product.reviews.empty?
                "No Ratings"
            else 
                product.avg_rating.round(2)
            end 
        end 
    end 

end

app/views/manufacturers/_search.html.erb
<%= form_with(url: "/manufacturers", method: :get, local: true ) do |f| %>
    <%= f.label "Find a Brand:" %>
    <%= f.text_field :search, value: "Brand Search" %>
    <%= f.submit "Search" %>
<% end %>

app/views/manufacturers/index.html.erb
<div>
    <%= render 'search' %>
</div>

<div>
        <% @manufacturers.each do |m| %>
            <ul>
            <li><%= link_to m.name, manufacturer_path(m) %></li>
            </ul>
        <% end %>
</div>

app/views/manufacturers/search.html.erb
<div>
<% @manufacturer.each do |m|%>
    <%= link_to m.name, manufacturer_path(m)%><br>
    <% end %>
</div>

app/views/manufacturers/show.html.erb
<%= @manufacturer.name %><br>
<%= @manufacturer.year_est %><br>

<%= link_to "Add New #{@manufacturer.name} Product", new_manufacturer_product_path(@manufacturer) %>

<div/>
<% @products.each do |product| %>
    <ul>
    <li><%= link_to product.name, product_path(product) %> - Rating:
        <% if !product.reviews.empty? %>
        <%= product.avg_rating %>
        <% else %>
            No Rating
        <% end %>
        <br>
    <%= product.category.name %></li> 
    </ul><br>
    <% end %>
</div>